### ISSUE TITLE
Don´t work oreo 8.1

### ISSUE THREAD

**Issue by manuelmagix** [Kra1o5/android_device_bq_bardock#2]
No monta ni reconoce el almacenamiento interno,

**Comment by phryneas** [comment]
Apparently this needs a new kernel.
The people in this thread created a modified version that supposedly works with 8.1.
https://www.android-hilfe.de/forum/root-custom-roms-modding-fuer-bq-aquaris-x-x-pro.3058/download-twrp-fuer-das-aquaris-x-x-pro.834301.html#post-11025444

It would be great if you could make an official release with that fix :)

**Comment by Kra1o5** [comment]
Hi, 
I will do a new release ASAP, like previously versions.
Changes submitted to TWRP.
New releases will be out soon.
